<!DOCTYPE HTML>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title></title>
</head>
<body>
  <script type="text/javascript" src="get-url.js"></script>
  <script type="text/javascript">
    /* 
       Calling `then` produces a new promise, whose result (the value
       passed to success handlers) depends on the return value of
       the first function we passed to then. 
         When the handler function returns a nonpromise
       value, the promise returned by `then` immediately succeeds
       with that value as its result.

       This means you can use `then` to transform the result of a
       promise. For example, this returns a promise whose result
       is the content of the given URL, parsed as JSON:
     */
    function getJSON(url) {
      return get(url).then(JSON.parse); /* getJSON returns a promise! */
      /*
         That last call to then did not specify a failure handler.
         This is allowed. The error will be passed to the promise
         returned by `then`, which is exactly what we want: 
           `getJSON` does not know what to do when something goes
           wrong, but hopefully its caller (`get(url)`) does.
       */
    }
    let info = getJSON("https://api.github.com/");
    console.log("1 GitHub API info = -- %o\n--", info); /* A promise object! */
    info.then(
        (x) => console.log("1 GitHub API info = -- %o+\n--",x) /* The JS object describing the GitHub API */ 
    ); 
  </script>
  <script type="text/javascript">
    let chuchu = getJSON("chuchu.json");
    chuchu.then(
        (x) => console.log("2 chuchu = -- %o+\n--",x) /* */ 
    ).catch(
        (e) => console.log("2 Catched!!! %o",e)
      ); 
    </script>
</body>
</html>

